apiVersion: v2
name: keycloak
description: Evaluation Keycloak chart (start-dev) for use with keycloak-jit-access
type: application
version: 0.1.0
appVersion: "26.3.3"
keywords:
  - keycloak
  - identity
  - pim
maintainers:
  - name: erreyesarroyo-cloud
